#视图解析器
spring:
  mvc:
    view:
      prefix: /jsps/  #前缀;
      suffix: .jsp    #后缀;
      static-path-pattern: /static/** #设置静态资源路径(url)格式;
  devtools: #开启热部署
    restart:
      enabled: true


#端口号
server:
  port: 8080



